-- Enable extension
create extension if not exists "pgcrypto";

-- =========================
-- JOBS
-- =========================
create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  title text,
  category text,
  type text,
  mode text,
  location text,
  experience text,
  description text,
  responsibilities jsonb,
  requirements jsonb,
  skills jsonb default '[]'::jsonb,
  tools jsonb default '[]'::jsonb,
  short_preview text,
  application_note text,
  nice_to_have jsonb default '[]'::jsonb,
  days_left integer default 30,
  salary_range text,
  positions integer default 1,
  role text,
  key_skills text,
  salary text
);

-- =========================
-- LATEST UPDATES
-- =========================
create table if not exists public.latest_updates (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  message text not null,
  action_text text,
  action_link text,
  is_active boolean default true,
  created_at timestamptz default now()
);

-- =========================
-- PRODUCTS
-- =========================
create table if not exists public.products (
  id bigint generated always as identity primary key,
  created_at timestamptz default now(),
  name text not null,
  category text,
  sub_category text,
  description text,
  key_highlights jsonb default '[]'::jsonb,
  crop_benefits jsonb default '[]'::jsonb,
  product_advantages jsonb default '[]'::jsonb,
  recommended_crops jsonb default '[]'::jsonb,
  application_timing text,
  recommended_dosage text,
  application_details text,
  image_url text
);

-- =========================
-- RESOURCES
-- =========================
create table if not exists public.resources (
  id uuid primary key default gen_random_uuid(),
  category text not null,
  title text not null,
  description text,
  detailed_description text,
  material_type text,
  image_url text,
  video_url text,
  file_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  is_active boolean default true
);

-- =========================
-- TESTIMONIALS
-- =========================
create table if not exists public.testimonials (
  id bigint generated always as identity primary key,
  created_at timestamptz default now(),
  title text not null,
  name text not null,
  state text,
  description text,
  video_url text,
  image_url text,
  image_src text,
  area text
);

-- Enable RLS
alter table public.resources enable row level security;
alter table public.products enable row level security;
alter table public.latest_updates enable row level security;

-- Drop old policies if any
drop policy if exists "Allow admin delete resources" on public.resources;
drop policy if exists "Allow admin insert resources" on public.resources;
drop policy if exists "Allow admin update resources" on public.resources;
drop policy if exists "Allow public read active resources" on public.resources;

drop policy if exists "Allow insert products" on public.products;
drop policy if exists "Allow public read products" on public.products;
drop policy if exists "Allow public update products" on public.products;

drop policy if exists "Allow admin insert" on public.latest_updates;
drop policy if exists "Allow admin update" on public.latest_updates;
drop policy if exists "Allow read active updates" on public.latest_updates;

-- =========================
-- RESOURCES POLICIES
-- =========================
create policy "Allow admin delete resources"
on public.resources for delete
to public using (true);

create policy "Allow admin insert resources"
on public.resources for insert
to public with check (true);

create policy "Allow admin update resources"
on public.resources for update
to public using (true);

create policy "Allow public read active resources"
on public.resources for select
to public using (is_active = true);

-- =========================
-- PRODUCTS POLICIES
-- =========================
create policy "Allow insert products"
on public.products for insert
to public with check (true);

create policy "Allow public read products"
on public.products for select
to public using (true);

create policy "Allow public update products"
on public.products for update
to public using (true) with check (true);

-- =========================
-- LATEST UPDATES POLICIES
-- =========================
create policy "Allow admin insert"
on public.latest_updates for insert
to public with check (true);

create policy "Allow admin update"
on public.latest_updates for update
to public using (true);

create policy "Allow read active updates"
on public.latest_updates for select
to public using (true);